-- 019: Animals as first-class records (Postgres)
-- Shifts can link to animals; volunteers log walk/feed/socialise activity.

CREATE TABLE IF NOT EXISTS animals (
  id                       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                     VARCHAR(255)  NOT NULL,
  species                  TEXT          NOT NULL DEFAULT 'dog'
                           CHECK (species IN ('dog','cat','small_animal','other')),
  breed                    VARCHAR(255)  DEFAULT NULL,
  sex                      VARCHAR(32)   DEFAULT NULL,
  date_of_birth            DATE          DEFAULT NULL,
  arrival_date             DATE          DEFAULT NULL,
  status                   TEXT          NOT NULL DEFAULT 'available'
                           CHECK (status IN ('available','reserved','adopted','foster','medical','not_for_rehoming')),
  kennel_ref               VARCHAR(64)   DEFAULT NULL,
  photo_filename           VARCHAR(255)  DEFAULT NULL,
  notes                    TEXT          DEFAULT NULL,
  handling_notes           TEXT          DEFAULT NULL,
  requires_qualification_id INTEGER      DEFAULT NULL,
  created_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_animals_qualification
    FOREIGN KEY (requires_qualification_id) REFERENCES qualifications (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_animals_species_status ON animals (species, status);
CREATE INDEX IF NOT EXISTS idx_animals_status ON animals (status);
CREATE INDEX IF NOT EXISTS fk_animals_qualification ON animals (requires_qualification_id);

DROP TRIGGER IF EXISTS trg_animals_updated_at ON animals;
CREATE TRIGGER trg_animals_updated_at
  BEFORE UPDATE ON animals
  FOR EACH ROW
  EXECUTE PROCEDURE set_updated_at();

CREATE TABLE IF NOT EXISTS opportunity_animals (
  opportunity_id  INTEGER NOT NULL,
  animal_id       INTEGER NOT NULL,
  PRIMARY KEY (opportunity_id, animal_id),
  CONSTRAINT fk_oa_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_oa_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS fk_oa_animal ON opportunity_animals (animal_id);

CREATE TABLE IF NOT EXISTS animal_activity (
  id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id        INTEGER       NOT NULL,
  user_id          INTEGER       NOT NULL,
  application_id   INTEGER       DEFAULT NULL,
  activity_type    TEXT          NOT NULL
                   CHECK (activity_type IN ('walk','feed','socialise','clean','medical','transport','other')),
  notes            TEXT          DEFAULT NULL,
  logged_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_aa_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_aa_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_aa_application
    FOREIGN KEY (application_id) REFERENCES applications (application_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_aa_animal_logged ON animal_activity (animal_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_aa_user ON animal_activity (user_id);
CREATE INDEX IF NOT EXISTS fk_aa_application ON animal_activity (application_id);
