-- 021: Foster placements — home suitability, requests, offers, placements

ALTER TABLE volunteer_profiles
  ADD COLUMN IF NOT EXISTS foster_approved SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS home_type TEXT DEFAULT NULL
    CHECK (home_type IS NULL OR home_type IN ('house','flat','other')),
  ADD COLUMN IF NOT EXISTS has_garden SMALLINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS garden_secure SMALLINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_other_dogs SMALLINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_other_cats SMALLINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_children_under_16 SMALLINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS can_medicate SMALLINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS max_foster_size TEXT DEFAULT NULL
    CHECK (max_foster_size IS NULL OR max_foster_size IN ('small','medium','large')),
  ADD COLUMN IF NOT EXISTS foster_notes TEXT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS foster_requests (
  id                       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id                INTEGER       NOT NULL,
  created_by               INTEGER       NOT NULL,
  urgency                  TEXT          NOT NULL DEFAULT 'planned'
                           CHECK (urgency IN ('planned','urgent')),
  needed_from              DATE          NOT NULL,
  expected_duration_days   INTEGER       DEFAULT NULL,
  requirements_json        TEXT          DEFAULT NULL,
  description              TEXT          DEFAULT NULL,
  status                   TEXT          NOT NULL DEFAULT 'open'
                           CHECK (status IN ('open','matched','cancelled')),
  created_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_foster_requests_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_requests_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_foster_requests_status ON foster_requests (status);
CREATE INDEX IF NOT EXISTS idx_foster_requests_animal ON foster_requests (animal_id);

CREATE TABLE IF NOT EXISTS foster_offers (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id   INTEGER       NOT NULL,
  user_id      INTEGER       NOT NULL,
  note         TEXT          DEFAULT NULL,
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status       TEXT          NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','accepted','withdrawn','rejected')),
  CONSTRAINT uq_foster_offer_request_user UNIQUE (request_id, user_id),
  CONSTRAINT fk_foster_offers_request
    FOREIGN KEY (request_id) REFERENCES foster_requests (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_offers_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_foster_offers_request ON foster_offers (request_id);
CREATE INDEX IF NOT EXISTS idx_foster_offers_user ON foster_offers (user_id);

CREATE TABLE IF NOT EXISTS foster_placements (
  id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id         INTEGER       NOT NULL,
  user_id           INTEGER       NOT NULL,
  request_id        INTEGER       DEFAULT NULL,
  started_on        DATE          NOT NULL,
  expected_end_on   DATE          DEFAULT NULL,
  ended_on          DATE          DEFAULT NULL,
  status            TEXT          NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active','ended','returned_early')),
  notes             TEXT          DEFAULT NULL,
  CONSTRAINT fk_foster_placements_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_placements_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_placements_request
    FOREIGN KEY (request_id) REFERENCES foster_requests (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_foster_placements_status ON foster_placements (status);
CREATE INDEX IF NOT EXISTS idx_foster_placements_user ON foster_placements (user_id);
CREATE INDEX IF NOT EXISTS idx_foster_placements_animal ON foster_placements (animal_id);
