-- 022: Threaded messaging (Postgres)
-- Shift / foster / transport threads with participants, soft-delete, digest log.

CREATE TABLE IF NOT EXISTS message_threads (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject       VARCHAR(255)  DEFAULT NULL,
  context_type  TEXT          NOT NULL
                CHECK (context_type IN (
                  'opportunity',
                  'foster_placement',
                  'transport_run',
                  'direct',
                  'announcement'
                )),
  context_id    INTEGER       DEFAULT NULL,
  created_by    INTEGER       NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at     TIMESTAMP     DEFAULT NULL,
  CONSTRAINT fk_message_threads_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_message_threads_context
  ON message_threads (context_type, context_id);
CREATE INDEX IF NOT EXISTS idx_message_threads_created_by
  ON message_threads (created_by);

CREATE TABLE IF NOT EXISTS thread_participants (
  thread_id     INTEGER       NOT NULL,
  user_id       INTEGER       NOT NULL,
  last_read_at  TIMESTAMP     DEFAULT NULL,
  muted         SMALLINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (thread_id, user_id),
  CONSTRAINT fk_thread_participants_thread
    FOREIGN KEY (thread_id) REFERENCES message_threads (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_thread_participants_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_thread_participants_user
  ON thread_participants (user_id);

CREATE TABLE IF NOT EXISTS messages (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id     INTEGER       NOT NULL,
  user_id       INTEGER       NOT NULL,
  body          TEXT          NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at    TIMESTAMP     DEFAULT NULL,
  deleted_by    INTEGER       DEFAULT NULL,
  CONSTRAINT fk_messages_thread
    FOREIGN KEY (thread_id) REFERENCES message_threads (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messages_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messages_deleted_by
    FOREIGN KEY (deleted_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_thread_created
  ON messages (thread_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_user
  ON messages (user_id);

-- One digest email per user per clock-hour (de-duplication for messageDigest job).
CREATE TABLE IF NOT EXISTS message_digest_log (
  user_id       INTEGER       NOT NULL,
  digest_hour   TIMESTAMP     NOT NULL,
  PRIMARY KEY (user_id, digest_hour),
  CONSTRAINT fk_message_digest_log_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
