-- 023: Shift notes pinned to opportunities (Postgres)

CREATE TABLE IF NOT EXISTS shift_notes (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id  INTEGER       NOT NULL,
  author_id       INTEGER       NOT NULL,
  body            TEXT          NOT NULL,
  notify          SMALLINT      NOT NULL DEFAULT 0,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_shift_notes_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_shift_notes_author
    FOREIGN KEY (author_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_shift_notes_opportunity_created
  ON shift_notes (opportunity_id, created_at DESC);
