-- 025: Hours certificates with public verification codes (Postgres)

CREATE TABLE IF NOT EXISTS certificates (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER       NOT NULL,
  code            VARCHAR(12)   NOT NULL,
  issued_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  hours_at_issue  DECIMAL(10,2) NOT NULL DEFAULT 0,
  shifts_at_issue INTEGER       NOT NULL DEFAULT 0,
  CONSTRAINT uq_certificates_code UNIQUE (code),
  CONSTRAINT fk_certificates_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_certificates_user_issued
  ON certificates (user_id, issued_at DESC);
