-- 027: AccessNI background checks + volunteer references

CREATE TABLE IF NOT EXISTS volunteer_references (
  id                    INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               INTEGER       NOT NULL,
  referee_name          VARCHAR(255)  NOT NULL,
  referee_email         VARCHAR(255)  NOT NULL,
  referee_relationship  VARCHAR(255)  DEFAULT NULL,
  requested_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  token_hash            VARCHAR(64)   NOT NULL,
  expires_at            TIMESTAMP     NOT NULL,
  responded_at          TIMESTAMP     DEFAULT NULL,
  is_suitable           SMALLINT      DEFAULT NULL,
  comments              TEXT          DEFAULT NULL,
  status                TEXT          NOT NULL DEFAULT 'requested'
                        CHECK (status IN ('requested','received','declined','expired')),
  CONSTRAINT uq_volunteer_references_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_volunteer_references_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_volunteer_references_user
  ON volunteer_references (user_id);
CREATE INDEX IF NOT EXISTS idx_volunteer_references_status
  ON volunteer_references (status);

CREATE TABLE IF NOT EXISTS background_checks (
  id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER       NOT NULL,
  check_type        TEXT          NOT NULL DEFAULT 'accessni_basic'
                    CHECK (check_type IN (
                      'accessni_basic',
                      'accessni_standard',
                      'accessni_enhanced',
                      'other'
                    )),
  reference_number  VARCHAR(100)  DEFAULT NULL,
  issued_on         DATE          DEFAULT NULL,
  expires_on        DATE          DEFAULT NULL,
  status            TEXT          NOT NULL DEFAULT 'not_required'
                    CHECK (status IN (
                      'not_required',
                      'requested',
                      'pending',
                      'clear',
                      'flagged',
                      'expired'
                    )),
  notes             TEXT          DEFAULT NULL,
  updated_by        INTEGER       DEFAULT NULL,
  updated_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_background_checks_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_background_checks_updated_by
    FOREIGN KEY (updated_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_background_checks_user
  ON background_checks (user_id);
CREATE INDEX IF NOT EXISTS idx_background_checks_status_expires
  ON background_checks (status, expires_on);

ALTER TABLE opportunities
  ADD COLUMN IF NOT EXISTS required_background_check_type TEXT DEFAULT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_opportunities_required_background_check_type'
  ) THEN
    ALTER TABLE opportunities
      ADD CONSTRAINT chk_opportunities_required_background_check_type
      CHECK (
        required_background_check_type IS NULL
        OR required_background_check_type IN (
          'accessni_basic',
          'accessni_standard',
          'accessni_enhanced',
          'other'
        )
      );
  END IF;
END $$;
