-- 028: Web push subscriptions + volunteer notification preferences

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER       NOT NULL,
  endpoint      TEXT          NOT NULL,
  p256dh        TEXT          NOT NULL,
  auth          TEXT          NOT NULL,
  user_agent    VARCHAR(255)  DEFAULT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_push_subscriptions_endpoint UNIQUE (endpoint),
  CONSTRAINT fk_push_subscriptions_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user
  ON push_subscriptions (user_id);

ALTER TABLE volunteer_profiles
  ADD COLUMN IF NOT EXISTS prefer_urgent SMALLINT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS prefer_reminders SMALLINT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS prefer_threads SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prefer_fosters SMALLINT NOT NULL DEFAULT 0;
