-- 029: Reusable opportunity templates for staff create flow

CREATE TABLE IF NOT EXISTS opportunity_templates (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(255)  NOT NULL,
  payload_json  TEXT          NOT NULL,
  created_by    INTEGER       DEFAULT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_opportunity_templates_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_opportunity_templates_created_by
  ON opportunity_templates (created_by);
