-- 030: Transport runs with claimable relay legs

CREATE TABLE IF NOT EXISTS transport_runs (
  id                  INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id           INTEGER       DEFAULT NULL,
  title               TEXT          NOT NULL,
  run_date            DATE          NOT NULL,
  notes               TEXT          DEFAULT NULL,
  status              TEXT          NOT NULL DEFAULT 'open'
                      CHECK (status IN ('open','part_covered','covered','completed','cancelled')),
  created_by          INTEGER       NOT NULL,
  created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  urgent_flagged_at   TIMESTAMP     DEFAULT NULL,
  CONSTRAINT fk_transport_runs_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_transport_runs_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_transport_runs_status ON transport_runs (status);
CREATE INDEX IF NOT EXISTS idx_transport_runs_run_date ON transport_runs (run_date);
CREATE INDEX IF NOT EXISTS idx_transport_runs_animal ON transport_runs (animal_id);

CREATE TABLE IF NOT EXISTS transport_legs (
  id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id            INTEGER       NOT NULL,
  leg_order         INTEGER       NOT NULL,
  from_location     TEXT          NOT NULL,
  to_location       TEXT          NOT NULL,
  depart_at         TIMESTAMP     DEFAULT NULL,
  arrive_by         TIMESTAMP     DEFAULT NULL,
  distance_miles    DECIMAL(8,2)  DEFAULT NULL,
  claimed_by        INTEGER       DEFAULT NULL,
  claimed_at        TIMESTAMP     DEFAULT NULL,
  completed_at      TIMESTAMP     DEFAULT NULL,
  notes             TEXT          DEFAULT NULL,
  expense_claimed   SMALLINT      NOT NULL DEFAULT 0,
  CONSTRAINT uq_transport_leg_order UNIQUE (run_id, leg_order),
  CONSTRAINT fk_transport_legs_run
    FOREIGN KEY (run_id) REFERENCES transport_runs (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_transport_legs_claimed_by
    FOREIGN KEY (claimed_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_transport_legs_run ON transport_legs (run_id);
CREATE INDEX IF NOT EXISTS idx_transport_legs_claimed_by ON transport_legs (claimed_by);
CREATE INDEX IF NOT EXISTS idx_transport_legs_unclaimed
  ON transport_legs (run_id) WHERE claimed_by IS NULL;
