-- 031: Staff-only incident / welfare notes

CREATE TABLE IF NOT EXISTS incidents (
  id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id        INTEGER       DEFAULT NULL,
  opportunity_id   INTEGER       DEFAULT NULL,
  reported_by      INTEGER       NOT NULL,
  body             TEXT          NOT NULL,
  severity         TEXT          NOT NULL DEFAULT 'concern'
                   CHECK (severity IN ('info','concern','urgent')),
  visibility       TEXT          NOT NULL DEFAULT 'staff_only'
                   CHECK (visibility IN ('staff_only')),
  created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at      TIMESTAMP     DEFAULT NULL,
  resolved_by      INTEGER       DEFAULT NULL,
  CONSTRAINT fk_incidents_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_reported_by
    FOREIGN KEY (reported_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_resolved_by
    FOREIGN KEY (resolved_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_incidents_animal ON incidents (animal_id);
CREATE INDEX IF NOT EXISTS idx_incidents_opportunity ON incidents (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_incidents_created ON incidents (created_at DESC);
