-- ============================================================================
-- ShelterLink — Full Database Schema (Postgres)
-- Converted from database/schema.sql. TINYINT flags stay SMALLINT (0/1).
-- ENUMs are TEXT + CHECK. IDENTITY is BY DEFAULT so seeds can set explicit ids.
-- Session storage is owned by connect-pg-simple (P4), not this file.
-- ============================================================================

DROP TABLE IF EXISTS
  opportunity_templates,
  push_subscriptions,
  background_checks,
  volunteer_references,
  certificates,
  shift_notes,
  message_digest_log,
  messages,
  thread_participants,
  message_threads,
  transport_legs,
  transport_runs,
  incidents,
  foster_placements,
  foster_offers,
  foster_requests,
  animal_photos,
  animal_activity,
  opportunity_animals,
  animals,
  group_bookings,
  audit_log,
  admin_messages,
  user_documents,
  waiver_acceptances,
  waivers,
  custom_field_values,
  custom_fields,
  tag_digest_log,
  opportunity_match_queue,
  opportunity_tags,
  volunteer_tags,
  tags,
  opportunity_qualifications,
  volunteer_qualifications,
  qualifications,
  job_runs,
  volunteer_hours,
  swap_requests,
  shift_feedback,
  applications,
  volunteer_profiles,
  opportunities,
  users,
  schema_migrations
CASCADE;

DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- users
-- ----------------------------------------------------------------------------
CREATE TABLE users (
  user_id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name          VARCHAR(100)  DEFAULT NULL,
  last_name           VARCHAR(100)  DEFAULT NULL,
  name                VARCHAR(200)  DEFAULT NULL,
  phone               VARCHAR(30)   DEFAULT NULL,
  email               VARCHAR(255)  NOT NULL,
  password            VARCHAR(255)  NOT NULL,
  role                TEXT          NOT NULL DEFAULT 'volunteer'
                      CHECK (role IN ('volunteer','staff','admin')),
  created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login          TIMESTAMP     DEFAULT NULL,
  anonymised_at       TIMESTAMP     DEFAULT NULL,
  reset_token         VARCHAR(64)   DEFAULT NULL,
  reset_token_expires TIMESTAMP     DEFAULT NULL,
  ical_token          VARCHAR(64)   DEFAULT NULL,
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_ical_token UNIQUE (ical_token)
);

CREATE INDEX idx_users_reset_token ON users (reset_token);
CREATE INDEX idx_users_role ON users (role);

-- ----------------------------------------------------------------------------
-- opportunities
-- ----------------------------------------------------------------------------
CREATE TABLE opportunities (
  opportunity_id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                   VARCHAR(255)  NOT NULL,
  description             TEXT          DEFAULT NULL,
  requirements            TEXT          DEFAULT NULL,
  location                VARCHAR(255)  DEFAULT NULL,
  start_date              TIMESTAMP     DEFAULT NULL,
  end_date                TIMESTAMP     DEFAULT NULL,
  max_volunteers          INTEGER       DEFAULT NULL,
  status                  TEXT          NOT NULL DEFAULT 'open'
                          CHECK (status IN ('open','closed','cancelled','completed')),
  created_by              INTEGER       DEFAULT NULL,
  recurrence_rule         TEXT          NOT NULL DEFAULT 'none'
                          CHECK (recurrence_rule IN ('none','daily','weekly')),
  recurrence_until        DATE          DEFAULT NULL,
  parent_opportunity_id   INTEGER       DEFAULT NULL,
  check_in_code           VARCHAR(6)    DEFAULT NULL,
  cancellation_cutoff_hours INTEGER     NOT NULL DEFAULT 24,
  activity_notes          TEXT          DEFAULT NULL,
  is_urgent               SMALLINT      NOT NULL DEFAULT 0,
  urgent_flagged_at       TIMESTAMP     DEFAULT NULL,
  required_background_check_type TEXT   DEFAULT NULL
                          CHECK (
                            required_background_check_type IS NULL
                            OR required_background_check_type IN (
                              'accessni_basic',
                              'accessni_standard',
                              'accessni_enhanced',
                              'other'
                            )
                          ),
  created_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_opportunities_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_opportunities_parent
    FOREIGN KEY (parent_opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_opportunities_status_start ON opportunities (status, start_date);
CREATE INDEX idx_opportunities_start_date ON opportunities (start_date);
CREATE INDEX idx_opportunities_urgent ON opportunities (is_urgent, start_date);
CREATE INDEX fk_opportunities_created_by ON opportunities (created_by);
CREATE INDEX fk_opportunities_parent ON opportunities (parent_opportunity_id);

-- ----------------------------------------------------------------------------
-- volunteer_profiles
-- ----------------------------------------------------------------------------
CREATE TABLE volunteer_profiles (
  profile_id        INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER       NOT NULL,
  date_of_birth     DATE          DEFAULT NULL,
  address           VARCHAR(255)  DEFAULT NULL,
  emergency_contact VARCHAR(255)  DEFAULT NULL,
  skills            TEXT          DEFAULT NULL,
  availability      VARCHAR(255)  DEFAULT NULL,
  approved          SMALLINT      NOT NULL DEFAULT 0,
  volunteer_type    TEXT          NOT NULL DEFAULT 'regular'
                    CHECK (volunteer_type IN ('regular','community_service','corporate_group')),
  required_hours    DECIMAL(8,2)  DEFAULT NULL,
  foster_approved   SMALLINT      NOT NULL DEFAULT 0,
  home_type         TEXT          DEFAULT NULL
                    CHECK (home_type IS NULL OR home_type IN ('house','flat','other')),
  has_garden        SMALLINT      DEFAULT NULL,
  garden_secure     SMALLINT      DEFAULT NULL,
  has_other_dogs    SMALLINT      DEFAULT NULL,
  has_other_cats    SMALLINT      DEFAULT NULL,
  has_children_under_16 SMALLINT  DEFAULT NULL,
  can_medicate      SMALLINT      DEFAULT NULL,
  max_foster_size   TEXT          DEFAULT NULL
                    CHECK (max_foster_size IS NULL OR max_foster_size IN ('small','medium','large')),
  foster_notes      TEXT          DEFAULT NULL,
  away_until        DATE          DEFAULT NULL,
  last_engagement_email_at TIMESTAMP DEFAULT NULL,
  prefer_urgent     SMALLINT      NOT NULL DEFAULT 1,
  prefer_reminders  SMALLINT      NOT NULL DEFAULT 1,
  prefer_threads    SMALLINT      NOT NULL DEFAULT 0,
  prefer_fosters    SMALLINT      NOT NULL DEFAULT 0,
  created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_profiles_user UNIQUE (user_id),
  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------------------------------------------
-- applications
-- ----------------------------------------------------------------------------
CREATE TABLE applications (
  application_id   INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          INTEGER       NOT NULL,
  opportunity_id   INTEGER       NOT NULL,
  status           TEXT          NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','accepted','approved','rejected','cancelled','waitlisted')),
  applied_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rejection_reason TEXT          DEFAULT NULL,
  notes            TEXT          DEFAULT NULL,
  reminder_sent_at TIMESTAMP     DEFAULT NULL,
  no_show          SMALLINT      NOT NULL DEFAULT 0,
  checked_in_at    TIMESTAMP     DEFAULT NULL,
  checked_out_at   TIMESTAMP     DEFAULT NULL,
  feedback_requested_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT uq_application_user_opportunity UNIQUE (user_id, opportunity_id),
  CONSTRAINT fk_applications_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_applications_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_applications_status ON applications (status);
CREATE INDEX idx_applications_opportunity_status ON applications (opportunity_id, status);
CREATE INDEX idx_applications_status_reminder ON applications (status, reminder_sent_at);

-- ----------------------------------------------------------------------------
-- shift_feedback
-- ----------------------------------------------------------------------------
CREATE TABLE shift_feedback (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id  INTEGER       NOT NULL,
  rating          SMALLINT      NOT NULL,
  comment         TEXT          DEFAULT NULL,
  flag_concern    SMALLINT      NOT NULL DEFAULT 0,
  handled_at      TIMESTAMP     DEFAULT NULL,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_feedback_application UNIQUE (application_id),
  CONSTRAINT fk_feedback_application
    FOREIGN KEY (application_id) REFERENCES applications (application_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_feedback_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_feedback_flag_handled ON shift_feedback (flag_concern, handled_at);
CREATE INDEX idx_feedback_created ON shift_feedback (created_at);

-- ----------------------------------------------------------------------------
-- swap_requests
-- ----------------------------------------------------------------------------
CREATE TABLE swap_requests (
  id                          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id              INTEGER       NOT NULL,
  requested_at                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status                      TEXT          NOT NULL DEFAULT 'open'
                              CHECK (status IN ('open','claimed','expired','cancelled')),
  claimed_by_application_id   INTEGER       DEFAULT NULL,
  waitlist_offered_to_user_id INTEGER       DEFAULT NULL,
  waitlist_offer_expires_at   TIMESTAMP     DEFAULT NULL,
  claim_token                 VARCHAR(64)   DEFAULT NULL,
  public_at                   TIMESTAMP     DEFAULT NULL,
  CONSTRAINT fk_swap_application
    FOREIGN KEY (application_id) REFERENCES applications (application_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_swap_claimed_by
    FOREIGN KEY (claimed_by_application_id) REFERENCES applications (application_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_swap_waitlist_user
    FOREIGN KEY (waitlist_offered_to_user_id) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_swap_status_public ON swap_requests (status, public_at);
CREATE INDEX idx_swap_claim_token ON swap_requests (claim_token);
CREATE INDEX fk_swap_application ON swap_requests (application_id);
CREATE INDEX fk_swap_claimed_by ON swap_requests (claimed_by_application_id);
CREATE INDEX fk_swap_waitlist_user ON swap_requests (waitlist_offered_to_user_id);

-- ----------------------------------------------------------------------------
-- volunteer_hours
-- ----------------------------------------------------------------------------
CREATE TABLE volunteer_hours (
  record_id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             INTEGER       NOT NULL,
  opportunity_id      INTEGER       DEFAULT NULL,
  date                DATE          NOT NULL,
  hours               DECIMAL(5,2)  NOT NULL,
  approved            SMALLINT      NOT NULL DEFAULT 0,
  verified_by_checkin SMALLINT      NOT NULL DEFAULT 0,
  created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_hours_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_hours_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_hours_user_approved ON volunteer_hours (user_id, approved);
CREATE INDEX idx_hours_approved_date ON volunteer_hours (approved, date);
CREATE INDEX fk_hours_opportunity ON volunteer_hours (opportunity_id);

-- ----------------------------------------------------------------------------
-- job_runs
-- ----------------------------------------------------------------------------
CREATE TABLE job_runs (
  id        INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name  VARCHAR(100)  NOT NULL,
  ran_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status    TEXT          NOT NULL CHECK (status IN ('ok','error')),
  detail    TEXT          DEFAULT NULL
);

CREATE INDEX idx_job_runs_name_ran ON job_runs (job_name, ran_at);

-- ----------------------------------------------------------------------------
-- qualifications
-- ----------------------------------------------------------------------------
CREATE TABLE qualifications (
  id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(255)  NOT NULL,
  description      TEXT          DEFAULT NULL,
  validity_months  INTEGER       DEFAULT NULL,
  created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_qualifications_name UNIQUE (name)
);

-- ----------------------------------------------------------------------------
-- volunteer_qualifications
-- ----------------------------------------------------------------------------
CREATE TABLE volunteer_qualifications (
  id                       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                  INTEGER       NOT NULL,
  qualification_id         INTEGER       NOT NULL,
  awarded_at               DATE          NOT NULL,
  expires_at               DATE          DEFAULT NULL,
  awarded_by               INTEGER       DEFAULT NULL,
  last_expiry_notified_at  DATE          DEFAULT NULL,
  created_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_volunteer_qualification UNIQUE (user_id, qualification_id),
  CONSTRAINT fk_vq_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_vq_qualification
    FOREIGN KEY (qualification_id) REFERENCES qualifications (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_vq_awarded_by
    FOREIGN KEY (awarded_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX fk_vq_qualification ON volunteer_qualifications (qualification_id);
CREATE INDEX fk_vq_awarded_by ON volunteer_qualifications (awarded_by);
CREATE INDEX idx_vq_expires ON volunteer_qualifications (expires_at);

-- ----------------------------------------------------------------------------
-- opportunity_qualifications
-- ----------------------------------------------------------------------------
CREATE TABLE opportunity_qualifications (
  opportunity_id    INTEGER NOT NULL,
  qualification_id  INTEGER NOT NULL,
  PRIMARY KEY (opportunity_id, qualification_id),
  CONSTRAINT fk_oq_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_oq_qualification
    FOREIGN KEY (qualification_id) REFERENCES qualifications (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX fk_oq_qualification ON opportunity_qualifications (qualification_id);

-- ----------------------------------------------------------------------------
-- tags
-- ----------------------------------------------------------------------------
CREATE TABLE tags (
  id    INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  VARCHAR(100)  NOT NULL,
  CONSTRAINT uq_tags_name UNIQUE (name)
);

CREATE TABLE volunteer_tags (
  user_id  INTEGER NOT NULL,
  tag_id   INTEGER NOT NULL,
  PRIMARY KEY (user_id, tag_id),
  CONSTRAINT fk_vt_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_vt_tag
    FOREIGN KEY (tag_id) REFERENCES tags (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX fk_vt_tag ON volunteer_tags (tag_id);

CREATE TABLE opportunity_tags (
  opportunity_id  INTEGER NOT NULL,
  tag_id          INTEGER NOT NULL,
  PRIMARY KEY (opportunity_id, tag_id),
  CONSTRAINT fk_ot_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ot_tag
    FOREIGN KEY (tag_id) REFERENCES tags (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX fk_ot_tag ON opportunity_tags (tag_id);

CREATE TABLE opportunity_match_queue (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id  INTEGER       NOT NULL,
  user_id         INTEGER       NOT NULL,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_match_queue_opp_user UNIQUE (opportunity_id, user_id),
  CONSTRAINT fk_omq_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_omq_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_match_queue_user ON opportunity_match_queue (user_id);

CREATE TABLE tag_digest_log (
  user_id      INTEGER NOT NULL,
  digest_date  DATE    NOT NULL,
  PRIMARY KEY (user_id, digest_date),
  CONSTRAINT fk_tdl_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO tags (name) VALUES
  ('dogs'),
  ('cats'),
  ('small animals'),
  ('cleaning'),
  ('events'),
  ('admin'),
  ('transport'),
  ('photography'),
  ('fundraising');

-- ----------------------------------------------------------------------------
-- custom_fields
-- ----------------------------------------------------------------------------
CREATE TABLE custom_fields (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label        VARCHAR(255)  NOT NULL,
  field_type   TEXT          NOT NULL DEFAULT 'text'
               CHECK (field_type IN ('text','select','checkbox','date')),
  options_json TEXT          DEFAULT NULL,
  required     SMALLINT      NOT NULL DEFAULT 0,
  applies_to   TEXT          NOT NULL DEFAULT 'profile'
               CHECK (applies_to IN ('profile')),
  sort_order   INTEGER       NOT NULL DEFAULT 0,
  active       SMALLINT      NOT NULL DEFAULT 1,
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_custom_fields_active_sort ON custom_fields (active, sort_order);

CREATE TABLE custom_field_values (
  id         INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id   INTEGER       NOT NULL,
  user_id    INTEGER       NOT NULL,
  value      TEXT          DEFAULT NULL,
  updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_custom_field_user UNIQUE (field_id, user_id),
  CONSTRAINT fk_cfv_field
    FOREIGN KEY (field_id) REFERENCES custom_fields (id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_cfv_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX fk_cfv_user ON custom_field_values (user_id);

CREATE TRIGGER trg_custom_field_values_updated_at
  BEFORE UPDATE ON custom_field_values
  FOR EACH ROW
  EXECUTE PROCEDURE set_updated_at();

-- ----------------------------------------------------------------------------
-- waivers
-- ----------------------------------------------------------------------------
CREATE TABLE waivers (
  id                     INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                  VARCHAR(255)  NOT NULL,
  body                   TEXT          NOT NULL,
  version                INTEGER       NOT NULL DEFAULT 1,
  active                 SMALLINT      NOT NULL DEFAULT 1,
  requires_reacceptance  SMALLINT      NOT NULL DEFAULT 1,
  created_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE waiver_acceptances (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  waiver_id    INTEGER       NOT NULL,
  user_id      INTEGER       NOT NULL,
  version      INTEGER       NOT NULL,
  accepted_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_waiver_user_version UNIQUE (waiver_id, user_id, version),
  CONSTRAINT fk_wa_waiver
    FOREIGN KEY (waiver_id) REFERENCES waivers (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_wa_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX fk_wa_user ON waiver_acceptances (user_id);

-- ----------------------------------------------------------------------------
-- user_documents
-- ----------------------------------------------------------------------------
CREATE TABLE user_documents (
  id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER       NOT NULL,
  filename       VARCHAR(255)  NOT NULL,
  original_name  VARCHAR(255)  NOT NULL,
  mime_type      VARCHAR(100)  NOT NULL,
  size           INTEGER       NOT NULL,
  uploaded_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at     DATE          DEFAULT NULL,
  label          VARCHAR(255)  DEFAULT NULL,
  content        BYTEA         DEFAULT NULL,
  CONSTRAINT fk_ud_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX fk_ud_user ON user_documents (user_id);

-- ----------------------------------------------------------------------------
-- admin_messages
-- ----------------------------------------------------------------------------
CREATE TABLE admin_messages (
  id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id         INTEGER       DEFAULT NULL,
  subject          VARCHAR(255)  NOT NULL,
  body             TEXT          NOT NULL,
  filter_json      TEXT          DEFAULT NULL,
  recipient_count  INTEGER       NOT NULL DEFAULT 0,
  created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_admin_messages_admin
    FOREIGN KEY (admin_id) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX fk_admin_messages_admin ON admin_messages (admin_id);

-- ----------------------------------------------------------------------------
-- audit_log
-- ----------------------------------------------------------------------------
CREATE TABLE audit_log (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER       DEFAULT NULL,
  action       VARCHAR(100)  NOT NULL,
  entity_type  VARCHAR(100)  DEFAULT NULL,
  entity_id    VARCHAR(64)   DEFAULT NULL,
  detail_json  JSON          DEFAULT NULL,
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_audit_created ON audit_log (created_at);
CREATE INDEX idx_audit_user ON audit_log (user_id);
CREATE INDEX idx_audit_action ON audit_log (action);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_id);

-- ----------------------------------------------------------------------------
-- group_bookings
-- ----------------------------------------------------------------------------
CREATE TABLE group_bookings (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id  INTEGER       NOT NULL,
  group_name      VARCHAR(255)  NOT NULL,
  contact_name    VARCHAR(255)  NOT NULL,
  contact_email   VARCHAR(255)  NOT NULL,
  size            INTEGER       NOT NULL,
  status          TEXT          NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','confirmed','cancelled')),
  notes           TEXT          DEFAULT NULL,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_group_bookings_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT chk_group_bookings_size CHECK (size > 0)
);

CREATE INDEX idx_group_bookings_status ON group_bookings (status);
CREATE INDEX idx_group_bookings_opportunity_status ON group_bookings (opportunity_id, status);

-- ----------------------------------------------------------------------------
-- animals
-- First-class shelter animals; shifts link via opportunity_animals.
-- ----------------------------------------------------------------------------
CREATE TABLE animals (
  id                       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                     VARCHAR(255)  NOT NULL,
  species                  TEXT          NOT NULL DEFAULT 'dog'
                           CHECK (species IN ('dog','cat','small_animal','other')),
  breed                    VARCHAR(255)  DEFAULT NULL,
  sex                      VARCHAR(32)   DEFAULT NULL,
  date_of_birth            DATE          DEFAULT NULL,
  arrival_date             DATE          DEFAULT NULL,
  status                   TEXT          NOT NULL DEFAULT 'available'
                           CHECK (status IN ('available','reserved','adopted','foster','medical','not_for_rehoming')),
  kennel_ref               VARCHAR(64)   DEFAULT NULL,
  photo_filename           VARCHAR(255)  DEFAULT NULL,
  notes                    TEXT          DEFAULT NULL,
  handling_notes           TEXT          DEFAULT NULL,
  requires_qualification_id INTEGER      DEFAULT NULL,
  created_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_animals_qualification
    FOREIGN KEY (requires_qualification_id) REFERENCES qualifications (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_animals_species_status ON animals (species, status);
CREATE INDEX idx_animals_status ON animals (status);
CREATE INDEX fk_animals_qualification ON animals (requires_qualification_id);

CREATE TRIGGER trg_animals_updated_at
  BEFORE UPDATE ON animals
  FOR EACH ROW
  EXECUTE PROCEDURE set_updated_at();

CREATE TABLE opportunity_animals (
  opportunity_id  INTEGER NOT NULL,
  animal_id       INTEGER NOT NULL,
  PRIMARY KEY (opportunity_id, animal_id),
  CONSTRAINT fk_oa_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_oa_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX fk_oa_animal ON opportunity_animals (animal_id);

CREATE TABLE animal_activity (
  id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id        INTEGER       NOT NULL,
  user_id          INTEGER       NOT NULL,
  application_id   INTEGER       DEFAULT NULL,
  activity_type    TEXT          NOT NULL
                   CHECK (activity_type IN ('walk','feed','socialise','clean','medical','transport','other')),
  notes            TEXT          DEFAULT NULL,
  logged_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_aa_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_aa_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_aa_application
    FOREIGN KEY (application_id) REFERENCES applications (application_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_aa_animal_logged ON animal_activity (animal_id, logged_at DESC);
CREATE INDEX idx_aa_user ON animal_activity (user_id);
CREATE INDEX fk_aa_application ON animal_activity (application_id);

-- Animal photo bytes, kept out of `animals` so list/detail SELECTs stay lean.
CREATE TABLE animal_photos (
  animal_id   INTEGER       NOT NULL PRIMARY KEY,
  content     BYTEA         NOT NULL,
  mime_type   VARCHAR(100)  NOT NULL DEFAULT 'image/jpeg',
  updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_animal_photos_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------------------------------------------
-- Foster requests, offers, and placements
-- ----------------------------------------------------------------------------
CREATE TABLE foster_requests (
  id                       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id                INTEGER       NOT NULL,
  created_by               INTEGER       NOT NULL,
  urgency                  TEXT          NOT NULL DEFAULT 'planned'
                           CHECK (urgency IN ('planned','urgent')),
  needed_from              DATE          NOT NULL,
  expected_duration_days   INTEGER       DEFAULT NULL,
  requirements_json        TEXT          DEFAULT NULL,
  description              TEXT          DEFAULT NULL,
  status                   TEXT          NOT NULL DEFAULT 'open'
                           CHECK (status IN ('open','matched','cancelled')),
  created_at               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_foster_requests_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_requests_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_foster_requests_status ON foster_requests (status);
CREATE INDEX idx_foster_requests_animal ON foster_requests (animal_id);

CREATE TABLE foster_offers (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id   INTEGER       NOT NULL,
  user_id      INTEGER       NOT NULL,
  note         TEXT          DEFAULT NULL,
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status       TEXT          NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','accepted','withdrawn','rejected')),
  CONSTRAINT uq_foster_offer_request_user UNIQUE (request_id, user_id),
  CONSTRAINT fk_foster_offers_request
    FOREIGN KEY (request_id) REFERENCES foster_requests (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_offers_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_foster_offers_request ON foster_offers (request_id);
CREATE INDEX idx_foster_offers_user ON foster_offers (user_id);

CREATE TABLE foster_placements (
  id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id         INTEGER       NOT NULL,
  user_id           INTEGER       NOT NULL,
  request_id        INTEGER       DEFAULT NULL,
  started_on        DATE          NOT NULL,
  expected_end_on   DATE          DEFAULT NULL,
  ended_on          DATE          DEFAULT NULL,
  status            TEXT          NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active','ended','returned_early')),
  notes             TEXT          DEFAULT NULL,
  CONSTRAINT fk_foster_placements_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_placements_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_foster_placements_request
    FOREIGN KEY (request_id) REFERENCES foster_requests (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_foster_placements_status ON foster_placements (status);
CREATE INDEX idx_foster_placements_user ON foster_placements (user_id);
CREATE INDEX idx_foster_placements_animal ON foster_placements (animal_id);

-- ----------------------------------------------------------------------------
-- transport runs (relay legs)
-- ----------------------------------------------------------------------------
CREATE TABLE transport_runs (
  id                  INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id           INTEGER       DEFAULT NULL,
  title               TEXT          NOT NULL,
  run_date            DATE          NOT NULL,
  notes               TEXT          DEFAULT NULL,
  status              TEXT          NOT NULL DEFAULT 'open'
                      CHECK (status IN ('open','part_covered','covered','completed','cancelled')),
  created_by          INTEGER       NOT NULL,
  created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  urgent_flagged_at   TIMESTAMP     DEFAULT NULL,
  CONSTRAINT fk_transport_runs_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_transport_runs_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_transport_runs_status ON transport_runs (status);
CREATE INDEX idx_transport_runs_run_date ON transport_runs (run_date);
CREATE INDEX idx_transport_runs_animal ON transport_runs (animal_id);

CREATE TABLE transport_legs (
  id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id            INTEGER       NOT NULL,
  leg_order         INTEGER       NOT NULL,
  from_location     TEXT          NOT NULL,
  to_location       TEXT          NOT NULL,
  depart_at         TIMESTAMP     DEFAULT NULL,
  arrive_by         TIMESTAMP     DEFAULT NULL,
  distance_miles    DECIMAL(8,2)  DEFAULT NULL,
  claimed_by        INTEGER       DEFAULT NULL,
  claimed_at        TIMESTAMP     DEFAULT NULL,
  completed_at      TIMESTAMP     DEFAULT NULL,
  notes             TEXT          DEFAULT NULL,
  expense_claimed   SMALLINT      NOT NULL DEFAULT 0,
  CONSTRAINT uq_transport_leg_order UNIQUE (run_id, leg_order),
  CONSTRAINT fk_transport_legs_run
    FOREIGN KEY (run_id) REFERENCES transport_runs (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_transport_legs_claimed_by
    FOREIGN KEY (claimed_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_transport_legs_run ON transport_legs (run_id);
CREATE INDEX idx_transport_legs_claimed_by ON transport_legs (claimed_by);

-- ----------------------------------------------------------------------------
-- incidents / welfare notes (staff only)
-- ----------------------------------------------------------------------------
CREATE TABLE incidents (
  id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal_id        INTEGER       DEFAULT NULL,
  opportunity_id   INTEGER       DEFAULT NULL,
  reported_by      INTEGER       NOT NULL,
  body             TEXT          NOT NULL,
  severity         TEXT          NOT NULL DEFAULT 'concern'
                   CHECK (severity IN ('info','concern','urgent')),
  visibility       TEXT          NOT NULL DEFAULT 'staff_only'
                   CHECK (visibility IN ('staff_only')),
  created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at      TIMESTAMP     DEFAULT NULL,
  resolved_by      INTEGER       DEFAULT NULL,
  CONSTRAINT fk_incidents_animal
    FOREIGN KEY (animal_id) REFERENCES animals (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_reported_by
    FOREIGN KEY (reported_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_resolved_by
    FOREIGN KEY (resolved_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_incidents_animal ON incidents (animal_id);
CREATE INDEX idx_incidents_opportunity ON incidents (opportunity_id);
CREATE INDEX idx_incidents_created ON incidents (created_at DESC);

-- ----------------------------------------------------------------------------
-- threaded messaging
-- ----------------------------------------------------------------------------
CREATE TABLE message_threads (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject       VARCHAR(255)  DEFAULT NULL,
  context_type  TEXT          NOT NULL
                CHECK (context_type IN (
                  'opportunity',
                  'foster_placement',
                  'transport_run',
                  'direct',
                  'announcement'
                )),
  context_id    INTEGER       DEFAULT NULL,
  created_by    INTEGER       NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at     TIMESTAMP     DEFAULT NULL,
  CONSTRAINT fk_message_threads_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_message_threads_context
  ON message_threads (context_type, context_id);
CREATE INDEX idx_message_threads_created_by
  ON message_threads (created_by);

CREATE TABLE thread_participants (
  thread_id     INTEGER       NOT NULL,
  user_id       INTEGER       NOT NULL,
  last_read_at  TIMESTAMP     DEFAULT NULL,
  muted         SMALLINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (thread_id, user_id),
  CONSTRAINT fk_thread_participants_thread
    FOREIGN KEY (thread_id) REFERENCES message_threads (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_thread_participants_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_thread_participants_user
  ON thread_participants (user_id);

CREATE TABLE messages (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id     INTEGER       NOT NULL,
  user_id       INTEGER       NOT NULL,
  body          TEXT          NOT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at    TIMESTAMP     DEFAULT NULL,
  deleted_by    INTEGER       DEFAULT NULL,
  CONSTRAINT fk_messages_thread
    FOREIGN KEY (thread_id) REFERENCES message_threads (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messages_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messages_deleted_by
    FOREIGN KEY (deleted_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_messages_thread_created
  ON messages (thread_id, created_at);
CREATE INDEX idx_messages_user
  ON messages (user_id);

CREATE TABLE message_digest_log (
  user_id       INTEGER       NOT NULL,
  digest_hour   TIMESTAMP     NOT NULL,
  PRIMARY KEY (user_id, digest_hour),
  CONSTRAINT fk_message_digest_log_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------------------------------------------
-- shift_notes
-- ----------------------------------------------------------------------------
CREATE TABLE shift_notes (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id  INTEGER       NOT NULL,
  author_id       INTEGER       NOT NULL,
  body            TEXT          NOT NULL,
  notify          SMALLINT      NOT NULL DEFAULT 0,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_shift_notes_opportunity
    FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_shift_notes_author
    FOREIGN KEY (author_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_shift_notes_opportunity_created
  ON shift_notes (opportunity_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- certificates
-- ----------------------------------------------------------------------------
CREATE TABLE certificates (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER       NOT NULL,
  code            VARCHAR(12)   NOT NULL,
  issued_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  hours_at_issue  DECIMAL(10,2) NOT NULL DEFAULT 0,
  shifts_at_issue INTEGER       NOT NULL DEFAULT 0,
  CONSTRAINT uq_certificates_code UNIQUE (code),
  CONSTRAINT fk_certificates_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_certificates_user_issued
  ON certificates (user_id, issued_at DESC);

-- ----------------------------------------------------------------------------
-- AccessNI / references (vetting)
-- ----------------------------------------------------------------------------
CREATE TABLE volunteer_references (
  id                    INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               INTEGER       NOT NULL,
  referee_name          VARCHAR(255)  NOT NULL,
  referee_email         VARCHAR(255)  NOT NULL,
  referee_relationship  VARCHAR(255)  DEFAULT NULL,
  requested_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  token_hash            VARCHAR(64)   NOT NULL,
  expires_at            TIMESTAMP     NOT NULL,
  responded_at          TIMESTAMP     DEFAULT NULL,
  is_suitable           SMALLINT      DEFAULT NULL,
  comments              TEXT          DEFAULT NULL,
  status                TEXT          NOT NULL DEFAULT 'requested'
                        CHECK (status IN ('requested','received','declined','expired')),
  CONSTRAINT uq_volunteer_references_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_volunteer_references_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_volunteer_references_user ON volunteer_references (user_id);
CREATE INDEX idx_volunteer_references_status ON volunteer_references (status);

CREATE TABLE background_checks (
  id                INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER       NOT NULL,
  check_type        TEXT          NOT NULL DEFAULT 'accessni_basic'
                    CHECK (check_type IN (
                      'accessni_basic',
                      'accessni_standard',
                      'accessni_enhanced',
                      'other'
                    )),
  reference_number  VARCHAR(100)  DEFAULT NULL,
  issued_on         DATE          DEFAULT NULL,
  expires_on        DATE          DEFAULT NULL,
  status            TEXT          NOT NULL DEFAULT 'not_required'
                    CHECK (status IN (
                      'not_required',
                      'requested',
                      'pending',
                      'clear',
                      'flagged',
                      'expired'
                    )),
  notes             TEXT          DEFAULT NULL,
  updated_by        INTEGER       DEFAULT NULL,
  updated_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_background_checks_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_background_checks_updated_by
    FOREIGN KEY (updated_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_background_checks_user ON background_checks (user_id);
CREATE INDEX idx_background_checks_status_expires ON background_checks (status, expires_on);

-- ----------------------------------------------------------------------------
-- Web push
-- ----------------------------------------------------------------------------
CREATE TABLE push_subscriptions (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER       NOT NULL,
  endpoint      TEXT          NOT NULL,
  p256dh        TEXT          NOT NULL,
  auth          TEXT          NOT NULL,
  user_agent    VARCHAR(255)  DEFAULT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_push_subscriptions_endpoint UNIQUE (endpoint),
  CONSTRAINT fk_push_subscriptions_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_push_subscriptions_user ON push_subscriptions (user_id);

-- ----------------------------------------------------------------------------
-- Opportunity templates
-- ----------------------------------------------------------------------------
CREATE TABLE opportunity_templates (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(255)  NOT NULL,
  payload_json  TEXT          NOT NULL,
  created_by    INTEGER       DEFAULT NULL,
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_opportunity_templates_created_by
    FOREIGN KEY (created_by) REFERENCES users (user_id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_opportunity_templates_created_by ON opportunity_templates (created_by);

-- ----------------------------------------------------------------------------
-- schema_migrations (used by scripts/migrate.js)
-- ----------------------------------------------------------------------------
CREATE TABLE schema_migrations (
  filename    VARCHAR(255) NOT NULL PRIMARY KEY,
  applied_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
